version: "3"
volumes:
  home:
  workspace:
    external:
      name: ${WORKSPACE}
  dot_ssh:
    external:
      name: ${DOT_SSH}
  entrypoint:
    external:
      name: ${ENTRYPOINT}
  bin:
    external:
      name: ${BIN}
  gitlab-config:
  gitlab-logs:
  gitlab-data:
services:
  chromium:
    image: tidyrailroad/chromium:0.0.0
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - home:/srv/home
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - workspace:/opt/workspace
  luckystar:
    image: wildwarehouse/cloud9:0.0.0
    volumes:
      - workspace:/opt/workspace
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command: --listen 0.0.0.0 -w /opt/workspace/workspace --auth user:password
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/logs/gitlab
      - gitlab-data:/var/opt/gitlab