version: "3"
volumes:
  homey:
    external:
      name: ${HOMEY}
  bin:
    external:
      name: ${BIN}
  sudo:
    external:
      name: ${SUDO}
  sbin:
    external:
      name: ${SBIN}
  gitlab-config:
  gitlab-logs:
  gitlab-data:
services:
  chromium:
    image: tidyrailroad/chromium:0.0.0
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - homey:/home
  luckystar:
    image: wildwarehouse/cloud9:0.0.0
    volumes:
      - homey:/home
      - bin:/usr/local/bin:ro
      - sudo:/etc/sudoers.d:ro
      - sbin:/usr/local/sbin:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command: --listen 0.0.0.0 -w /home/user/workspace --auth user:password
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/logs/gitlab
      - gitlab-data:/var/opt/gitlab